### ISSUE TITLE
[html2md.py] get_title with double spacing

### ISSUE THREAD

**Issue by dltmddbs100** [taeminlee/tomok2md#3]
json과 chunks.json을 title값으로 merge하는 과정에서 mismatch가 발생

- 현재 html2md.py의 get_title 함수로 title(예:1.2 용어정의) 을 파싱할때 텍스트(용어정의) 부분의 중복 스페이스 고려가 안되어있어, 중복 공백이 존재하는 일부 항목의 title이 chunks.json에서 잘리는 현상이 발생

=> html2md.py의 719번째줄을 

title_tree = html.fromstring(re.sub(' +',' ',self.doc['contentsView']), parser=html.HTMLParser()) 

로 변경이 필요. 이후 매칭잘되는 것 확인.

**Comment by taeminlee** [comment]
코드 반영했습니다.
